### ISSUE TITLE
Feature request - Additional 

### ISSUE THREAD

**Issue by CastleSoft** [VSoftTechnologies/VSoft.UUIDv7#1]
type
  TUUIDV7Helper = record
    class function CreateV7: TGuid; static;
    class function CreateV7(timestamp: TDateTime): TGuid; static;
  end;
  
class function TUUIDV7Helper.CreateV7(timestamp: TDateTime): TGuid;
var
  unixTimestamp: UInt64;
begin
  result := TGUID.NewGuid;
  unixTimestamp := DateTimeToUnixMilliseconds(timestamp);
  result.D1 := Cardinal(unixTimestamp shr 16);
  result.D2 := Word(unixTimestamp);
  result.D3 := (result.D3 and (not VersionMask)) or Version7Value;
  result.D4[0] := (result.D4[0] and (not Variant10xxMask)) or Variant10xxValue;
end;

Pseudo coded / not tested suggestion / feature request

**Comment by vincentparrett** [comment]
Done. Note that this method is much slower - not an issue unless you need to generate a lot of guids quickly.
